server:
  port: 80

# 连接池配置
spring:
  application:
    name: STU

#数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: root


#开发热部署配置,在运行时也能热修改,使用ctrl+F9构建项目保存修改
  devtools:
    restart:
      enabled: true #生效
      additional-paths: src/main/java #监听目录
      exclude: static/**



#Mybatis配置
mybatis:
  mapper-locations: /src/main/resources/mapper/*.xml
  type-aliases-package: stu.pojo
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出sal语句
  type-aliases-package: stu.pojo

#日志配置
#logging:
#  level:
#    top.crcbest: debug
#  pattern:
#    console: [%-5level] %d{yyyy-MM-dd HH:mm:ss} %c [%thread] 等级：%msg %n
#    file: ./log
#  config:




